event_inherited();
max_hp = 100;
current_hp = max_hp;
attack=spr_JappaHat_Attack;
idle=spr_JappaHat_Idle;
hit=spr_JappaHat_Hit;
move=spr_JappaHat_Move;
jump=spr_JappaHat_Move;
fall=spr_JappaHat_Move;
death=spr_death;
Attacks=[{name:"hit",damage:7,animation:attack}];